"""Isolated execution of model-written test code.

Threat model (stated honestly)
------------------------------
Everything Blindspot executes is code that a language model just wrote.  This
sandbox is designed to contain **accidents**, which is the realistic failure
mode: infinite loops, runaway memory, accidental network calls, tests that
scribble into the developer's working tree, and non-determinism that would
break replay.

It is *not* a security boundary against deliberately hostile code, and **no
container mode is shipped**.  Everything here runs as the calling user in a
temporary directory; a determined escape is not defended against.  That is
acceptable for this project, whose inputs are code the *same operator* just
asked a model to write, and it would not be acceptable for auditing code from
an untrusted source -- that would want a container or a VM, and would be real
work rather than a flag.

The distinction is stated rather than glossed because Rule Book #04 asks for
consequential actions to be controlled, and an honest statement of what is and
is not controlled is part of that.

Guarantees provided here:

* fresh temporary directory per run, deleted afterwards; ``cwd`` is that
  directory, so relative writes cannot touch the repository;
* hard wall-clock timeout with process-tree kill;
* address-space cap on POSIX (``RLIMIT_AS``);
* sockets disabled inside the test process;
* ``PYTHONHASHSEED=0`` and a derandomised Hypothesis profile, so a property
  test that fails once fails identically forever.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from ..types import ProbeResult, RunStatus

# Injected into every sandbox.  Kept as a literal (not a packaged file) so the
# sandbox has no dependency on Blindspot being importable inside it.
CONFTEST = '''\
"""Auto-generated by Blindspot. Determinism + isolation for probe execution."""
import os
import socket
import sys

# --- no network -------------------------------------------------------------
class _BlockedSocket(socket.socket):
    def __init__(self, *args, **kwargs):
        raise OSError("network access is disabled inside the Blindspot sandbox")


def _blocked(*args, **kwargs):
    raise OSError("network access is disabled inside the Blindspot sandbox")


socket.socket = _BlockedSocket           # type: ignore[misc,assignment]
socket.create_connection = _blocked      # type: ignore[assignment]
socket.getaddrinfo = _blocked            # type: ignore[assignment]

# --- determinism ------------------------------------------------------------
try:
    import random
    random.seed(0)
except Exception:
    pass

try:
    from hypothesis import HealthCheck, settings

    settings.register_profile(
        "blindspot",
        derandomize=True,
        deadline=None,
        database=None,
        max_examples=int(os.environ.get("BLINDSPOT_HYPOTHESIS_EXAMPLES", "120")),
        suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
        print_blob=False,
    )
    settings.load_profile("blindspot")
except Exception:
    pass

sys.path.insert(0, os.path.dirname(__file__))
'''

_ASSERTION = re.compile(r"^E\s+(.*)$", re.M)
_FALSIFYING = re.compile(r"Falsifying example: (.*?)(?:\n\n|\Z)", re.S)
_HYP_ARGS = re.compile(r"^\s{4}(\w+=.*)$", re.M)

# Signals that the *probe* is broken rather than the implementation.
_PROBE_BROKEN = re.compile(
    r"""^E\s+(?:
          ImportError
        | ModuleNotFoundError
        | SyntaxError
        | IndentationError
        | NameError
        | AttributeError:\s+module\s+'impl'
        | TypeError:\s+\w+\(\)\s+(?:got|missing|takes)
        | fixture\s+'\w+'\s+not\s+found
        | OSError:\s+network\ access\ is\ disabled
    )""",
    re.M | re.X,
)

# Anything machine-specific must be scrubbed before a result is persisted,
# otherwise `make reproduce` cannot be byte-identical across machines.
_NONDETERMINISM = [
    (re.compile(r"0x[0-9a-fA-F]{6,}"), "0xADDR"),
    (re.compile(r"(?i)[A-Z]:\\\\?[^\s'\"]*blindspot-sbx-[^\s'\"]*"), "<sandbox>"),
    (re.compile(r"/tmp/blindspot-sbx-[^\s'\"]*"), "<sandbox>"),
    (re.compile(r"\bin \d+\.\d+s\b"), "in <t>s"),
    (re.compile(r"(?m)^rootdir: .*$"), "rootdir: <sandbox>"),
    (re.compile(r"(?m)^plugins: .*$"), "plugins: <pinned>"),
    (re.compile(r"at 0xADDR>"), ">"),
]


def normalise(text: str) -> str:
    """Strip machine-specific noise (addresses, temp paths, timings)."""
    for pattern, replacement in _NONDETERMINISM:
        text = pattern.sub(replacement, text)
    return text


@dataclass
class SandboxSpec:
    """A complete, self-contained file tree to execute."""

    files: dict[str, str] = field(default_factory=dict)
    entry: str = "test_probe.py"
    timeout_s: float = 20.0
    max_memory_mb: int = 2048
    env: dict[str, str] = field(default_factory=dict)
    runner: str = "pytest"  # "pytest" | "script"
    # Probe output is capped tightly because it lands in prompts and
    # trajectories.  Driver scripts return structured JSON on one line and must
    # not be truncated, so they raise this deliberately.
    max_output_chars: int = 8_000


def _preexec(max_memory_mb: int) -> Callable[[], None] | None:  # pragma: no cover - POSIX only
    """Address-space cap and a fresh session, on platforms that have them.

    `resource` and `os.setsid` do not exist on Windows, so they are resolved
    dynamically: importing them by name would make this module fail to
    type-check on the platform most of this was developed on.
    """
    try:
        import resource
    except ImportError:
        return None

    setrlimit = getattr(resource, "setrlimit", None)
    rlimit_as = getattr(resource, "RLIMIT_AS", None)
    setsid = getattr(os, "setsid", None)
    if setrlimit is None or rlimit_as is None:
        return None

    def _apply() -> None:
        limit = max_memory_mb * 1024 * 1024
        setrlimit(rlimit_as, (limit, limit))
        if setsid is not None:
            setsid()

    return _apply


def _first_assertion(text: str) -> str:
    """The headline failure line.

    pytest prints the primary assertion first and then continuation lines
    beginning with ``+`` or ``where``; those explain but do not summarise, so
    the first non-continuation line is the one worth surfacing.
    """
    matches = [m.strip() for m in _ASSERTION.findall(text)]
    for candidate in matches:
        if candidate and not candidate.startswith(("+", "and", "where", "-")):
            return candidate[:600]
    return matches[0][:600] if matches else ""


def _falsifying_input(text: str) -> str:
    match = _FALSIFYING.search(text)
    if match:
        args = _HYP_ARGS.findall(match.group(1))
        if args:
            return ", ".join(a.strip() for a in args)[:400]
        return match.group(1).strip().splitlines()[0][:400]
    # Fall back to a `blindspot_input = ...` marker that probes are asked to set.
    marker = re.search(r"blindspot_input\s*=\s*(.+)", text)
    if marker:
        return marker.group(1).strip()[:400]
    return ""


def run(spec: SandboxSpec) -> ProbeResult:
    """Execute ``spec`` and classify the outcome."""
    workdir = Path(tempfile.mkdtemp(prefix="blindspot-sbx-"))
    try:
        for relative, content in spec.files.items():
            target = workdir / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
        (workdir / "conftest.py").write_text(CONFTEST, encoding="utf-8")

        env = {
            **os.environ,
            "PYTHONHASHSEED": "0",
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONNOUSERSITE": "1",
            "PYTHONIOENCODING": "utf-8",
            "NO_COLOR": "1",
            "TZ": "UTC",
            # Third-party pytest plugins installed on the *host* are a real
            # reproducibility hazard: they change collection order, add reruns,
            # and -- as found on the development machine -- open sockets during
            # `pytest_configure`.  A probe's verdict must depend on the code
            # under test, never on what happens to be pip-installed nearby.
            "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1",
            **spec.env,
        }
        env.pop("PYTEST_ADDOPTS", None)

        # NOTE: deliberately *not* using `python -I`.  Isolated mode implies
        # `-E`, which would discard PYTHONHASHSEED and reintroduce hash
        # randomisation -- the exact non-determinism this sandbox exists to
        # remove.  Isolation from user site-packages is achieved with
        # PYTHONNOUSERSITE instead.
        if spec.runner == "script":
            argv = [sys.executable, spec.entry]
        else:
            argv = [
                sys.executable,
                "-m",
                "pytest",
                spec.entry,
                "-q",
                "--no-header",
                "-p",
                "no:cacheprovider",
                # Hypothesis' pytest plugin is re-enabled explicitly because
                # plugin autoloading is switched off above.  It is the one
                # plugin probes are allowed to rely on.
                "-p",
                "_hypothesis_pytestplugin",
                "--tb=short",
                "-x",
            ]

        started = time.monotonic()
        try:
            proc = subprocess.run(
                argv,
                cwd=str(workdir),
                env=env,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=spec.timeout_s,
                preexec_fn=_preexec(spec.max_memory_mb) if os.name == "posix" else None,
            )
        except subprocess.TimeoutExpired as exc:
            return ProbeResult(
                status=RunStatus.TIMEOUT,
                duration_ms=int(spec.timeout_s * 1000),
                stdout=(exc.stdout or b"").decode("utf-8", "replace")[-4000:]
                if isinstance(exc.stdout, bytes)
                else (exc.stdout or "")[-4000:],
                stderr=f"timed out after {spec.timeout_s}s",
                exit_code=-1,
            )
        duration_ms = int((time.monotonic() - started) * 1000)

        combined = normalise(f"{proc.stdout}\n{proc.stderr}")
        if spec.runner == "script":
            status = RunStatus.PASS if proc.returncode == 0 else RunStatus.ERROR
        else:
            status = _classify(proc.returncode, combined)
        return ProbeResult(
            status=status,
            duration_ms=duration_ms,
            stdout=normalise(proc.stdout)[-spec.max_output_chars :],
            stderr=normalise(proc.stderr)[-max(4000, spec.max_output_chars // 2) :],
            assertion=_first_assertion(combined) if status is RunStatus.FAIL else "",
            failing_input=_falsifying_input(combined) if status is RunStatus.FAIL else "",
            exit_code=proc.returncode,
        )
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _classify(returncode: int, output: str) -> RunStatus:
    """Map pytest's exit code to a probe outcome.

    The distinction that matters is FAIL (an assertion was violated -- possible
    counterexample) versus ERROR (the probe could not even run -- the model got
    the API wrong and should be given the traceback and asked to repair).
    """
    if returncode == 0:
        return RunStatus.PASS
    if returncode == 5:  # no tests collected
        return RunStatus.ERROR
    if returncode in (2, 3, 4):  # interrupted / internal / usage error
        return RunStatus.ERROR
    if returncode == 1:
        # pytest reports collection errors as exit 1 too; distinguish by text.
        if "errors during collection" in output or "ERROR collecting" in output:
            return RunStatus.ERROR
        # A probe that blows up on *how* it calls the code is broken, not
        # evidence about the implementation's behaviour.  These are handed back
        # to the adversary with the traceback so it can repair the call.
        if _PROBE_BROKEN.search(output):
            return RunStatus.ERROR
        return RunStatus.FAIL
    return RunStatus.ERROR


def run_probe(
    *,
    probe_code: str,
    impl_source: str,
    timeout_s: float = 20.0,
    extra_files: dict[str, str] | None = None,
    hypothesis_examples: int = 120,
    timeout_retries: int = 3,
) -> ProbeResult:
    """Run one probe module against an implementation.

    The implementation is always written as ``impl.py``, so the identical probe
    can be executed against the candidate and against the hidden reference --
    which is exactly what the grader needs to decide whether a counterexample
    is *sound*.
    """
    files = {"impl.py": impl_source, "test_probe.py": probe_code}
    if extra_files:
        files.update(extra_files)

    # A timeout is an inconclusive *measurement*, not an observation about the
    # code, and it must not be allowed to change the pipeline's path.  Many
    # probes run concurrently, and a property-based one that normally finishes
    # in a second can exceed the limit purely because the machine is busy.  When
    # that happened the adversary saw `TIMEOUT`, treated it as a broken probe
    # and spent repair attempts on it -- so two replays of the *same* cassettes
    # diverged, one emitting a test the other did not.  That is precisely the
    # failure a reproduction guarantee exists to exclude.
    #
    # Retrying with more headroom costs nothing when nothing times out, and a
    # probe still unfinished at triple the budget is genuinely too slow to be
    # evidence.
    result = ProbeResult(status=RunStatus.TIMEOUT)
    for attempt in range(timeout_retries):
        result = run(
            SandboxSpec(
                files=files,
                entry="test_probe.py",
                timeout_s=timeout_s * (1 + attempt),
                env={"BLINDSPOT_HYPOTHESIS_EXAMPLES": str(hypothesis_examples)},
            )
        )
        if result.status is not RunStatus.TIMEOUT:
            break
    return result


def run_suite(
    *,
    suite_code: str,
    impl_source: str,
    timeout_s: float = 60.0,
    suite_name: str = "test_suite.py",
) -> ProbeResult:
    """Run a whole test suite (used for a case's self-written tests)."""
    return run(
        SandboxSpec(
            files={"impl.py": impl_source, suite_name: suite_code},
            entry=suite_name,
            timeout_s=timeout_s,
        )
    )
