"""Content-addressed record/replay for model calls.

Why this exists
---------------
The competition rule book requires that judges can reproduce the headline
result, and the organiser explicitly does **not** supply API keys.  A benchmark
whose numbers can only be regenerated by someone holding a paid key is, for
practical purposes, not reproducible.

So every model call is hashed on ``(system, user, model, temperature,
max_tokens, purpose, nonce)`` and its response is committed to ``cassettes/``.
``make reproduce`` then replays the entire benchmark offline, deterministically
and with no credentials at all.  It is not quick -- every generated test is
re-executed for real -- but nothing in it needs a model or a network.

Repeat handling
---------------
The same request can legitimately occur more than once inside a run (a retry
after a sandbox error re-issues an identical prompt).  Recordings are therefore
stored as ``<key>.<seq>.json`` and replayed in order: the *n*-th occurrence of a
key during replay returns the *n*-th recording, exactly as it happened live.
The final recording for a key is reused if replay asks for more occurrences
than were recorded, which keeps replay total even when a run takes a slightly
different path.

The cassette files double as the "agent trajectories" deliverable: each one
contains the full prompt that was sent and the full text that came back.
"""

from __future__ import annotations

import json
import threading
from collections import defaultdict
from pathlib import Path
from typing import Any

from .base import CassetteMiss, LLMRequest, LLMResponse

CASSETTE_FORMAT = 1


class CassetteStore:
    """Filesystem-backed store of recorded completions."""

    def __init__(self, root: Path, *, strict: bool = True) -> None:
        self.root = Path(root)
        self.strict = strict
        # Keyed by (scope, cache_key).  The scope is the run id, so two runs
        # executing concurrently against one shared store cannot disturb each
        # other's occurrence sequence -- see `reserve`.
        self._counters: dict[tuple[str, str], int] = defaultdict(int)
        self._record_counters: dict[str, int] = defaultdict(int)
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0
        self.writes = 0

    # ------------------------------------------------------------------ #
    # Layout
    # ------------------------------------------------------------------ #

    def _dir_for(self, key: str) -> Path:
        return self.root / key[:2]

    def _path(self, key: str, seq: int) -> Path:
        return self._dir_for(key) / f"{key}.{seq}.json"

    def _available(self, key: str) -> int:
        directory = self._dir_for(key)
        if not directory.is_dir():
            return 0
        return sum(1 for _ in directory.glob(f"{key}.*.json"))

    # ------------------------------------------------------------------ #
    # Replay
    # ------------------------------------------------------------------ #

    def reserve(self, request: LLMRequest, scope: str = "") -> tuple[str, int]:
        """Claim this run's occurrence index for a prompt.

        Occurrence indices are per-key **and per-scope**, which is what lets an
        identical prompt issued twice in one run replay as two distinct
        recordings rather than the same one twice.

        ``scope`` is the run id.  It exists because the sweep shares one store
        across concurrently executing runs: the previous design kept a single
        global counter and cleared it at the start of each case, so one job's
        reset silently renumbered another job's in-flight lookups.  That made a
        replay take a different path from the run it was replaying -- the exact
        failure a reproduction guarantee is supposed to exclude.
        """
        key = request.cache_key()
        with self._lock:
            seq = self._counters[(scope, key)]
            self._counters[(scope, key)] = seq + 1
        return key, seq

    def take(self, request: LLMRequest, scope: str = "") -> tuple[str, int, LLMResponse | None]:
        """Reserve an occurrence index and return its recording if one exists.

        This is what makes **recording resumable**.  A live recording run that
        dies half way -- a usage limit, a dropped connection, a laptop lid --
        can be restarted with the same command: every call it already captured
        replays for free, and only the calls it never reached are paid for.
        Without this, an interrupted recording would re-buy the whole sweep.
        """
        key, seq = self.reserve(request, scope)
        if seq < self._available(key):
            return key, seq, self._read(key, seq, requested=seq)
        return key, seq, None

    def _read(self, key: str, effective: int, *, requested: int) -> LLMResponse:
        path = self._path(key, effective)
        if not path.is_file():
            self.misses += 1
            raise CassetteMiss(f"Cassette index {effective} missing for key {key[:12]}")
        data = json.loads(path.read_text(encoding="utf-8"))
        self.hits += 1
        response = LLMResponse.from_dict(data["response"])
        response.meta["cassette"] = str(path.relative_to(self.root))
        response.meta["replayed"] = True
        response.meta["replay_seq"] = requested
        response.meta["replay_clamped"] = effective != requested
        return response

    def replay(self, request: LLMRequest, key: str, seq: int) -> LLMResponse:
        """Read occurrence ``seq``, clamping to the last recording.

        Clamping rather than failing keeps replay a *total* function: a replayed
        run that takes one extra retry than the recorded one still resolves,
        instead of aborting the whole sweep over a single extra step.
        """
        available = self._available(key)
        if available == 0:
            self.misses += 1
            raise CassetteMiss(
                f"No cassette for purpose={request.purpose!r} model={request.model!r} "
                f"key={key[:12]}.\n"
                "Nothing was recorded for this exact prompt. Either the prompts changed "
                "since the cassettes were recorded, or you are running a configuration "
                "that was never recorded.\n"
                "Fix: re-record with `make record` (needs model access), or run a "
                "configuration that has cassettes -- see cassettes/MANIFEST.json."
            )
        return self._read(key, min(seq, available - 1), requested=seq)

    def lookup(self, request: LLMRequest, scope: str = "") -> LLMResponse:
        key, seq = self.reserve(request, scope)
        return self.replay(request, key, seq)

    def has(self, request: LLMRequest) -> bool:
        return self._available(request.cache_key()) > 0

    # ------------------------------------------------------------------ #
    # Record
    # ------------------------------------------------------------------ #

    def record(
        self,
        request: LLMRequest,
        response: LLMResponse,
        *,
        key: str | None = None,
        seq: int | None = None,
    ) -> Path:
        """Persist a completion.

        ``key``/``seq`` are supplied by the router when the call came through
        :meth:`take`, so the recording lands at the same occurrence index the
        run asked for.  Without them the store falls back to its own append
        counter, which is what the unit tests use.
        """
        key = key if key is not None else request.cache_key()
        if seq is None:
            with self._lock:
                seq = self._record_counters[key]
                self._record_counters[key] = seq + 1

        path = self._path(key, seq)
        path.parent.mkdir(parents=True, exist_ok=True)
        payload: dict[str, Any] = {
            "format": CASSETTE_FORMAT,
            "key": key,
            "seq": seq,
            "request": request.cache_payload(),
            "response": response.to_dict(),
        }
        path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        self.writes += 1
        return path

    # ------------------------------------------------------------------ #
    # Bookkeeping
    # ------------------------------------------------------------------ #

    def reset_counters(self, scope: str = "") -> None:
        """Drop the occurrence counters for one scope, or all of them.

        Retained for single-run callers.  The sweep no longer uses it: clearing
        shared state while other runs are mid-flight is what made replays
        diverge from the runs they replayed.
        """
        with self._lock:
            if scope:
                for entry in [k for k in self._counters if k[0] == scope]:
                    del self._counters[entry]
            else:
                self._counters.clear()

    def manifest(self) -> dict[str, Any]:
        files = sorted(self.root.rglob("*.json"))
        files = [f for f in files if f.name != "MANIFEST.json"]
        models: dict[str, int] = defaultdict(int)
        purposes: dict[str, int] = defaultdict(int)
        total_in = total_out = 0
        for f in files:
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
            except json.JSONDecodeError:  # pragma: no cover - corrupt file
                continue
            models[data["request"]["model"]] += 1
            purposes[data["request"]["purpose"]] += 1
            total_in += int(data["response"].get("input_tokens", 0))
            total_out += int(data["response"].get("output_tokens", 0))
        return {
            "format": CASSETTE_FORMAT,
            "recordings": len(files),
            "by_model": dict(sorted(models.items())),
            "by_purpose": dict(sorted(purposes.items())),
            "input_tokens": total_in,
            "output_tokens": total_out,
        }

    def write_manifest(self) -> Path:
        path = self.root / "MANIFEST.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.manifest(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        return path

    def stats(self) -> dict[str, int]:
        return {"hits": self.hits, "misses": self.misses, "writes": self.writes}
