"""Spec-anchored adjudication applied to *somebody else's* tests.

The held-out result made the project's original claim untenable: withholding
the implementation from the test generator does not find more defects, it finds
far fewer, because a generator working from the specification alone never
guesses the one input that breaks the code.  What the barrier demonstrably buys
is **precision** — 4% false alarms against 35-38% for the two baselines.

That suggests the contribution is separable from the search.  If the valuable
part is a specification-anchored reading that never sees the accusation, it
should improve *any* generator's output, including one that reads the code and
is better at finding candidates than Blindspot is.

So this stage takes tests produced by an arbitrary system, runs them, and puts
every red one in front of the Oracle:

    test fails on the candidate  ->  Oracle predicts the required result from
                                     the specification and the call alone
                                 ->  mechanical comparison with the assertion
                                 ->  disagreement withdraws the test

Nothing here reads the implementation, and the Oracle never sees the test's
source or its author's reasoning.  It can only ever remove a test, so it cannot
manufacture a detection: any change in detection rate is a cost, and any change
in false-alarm rate is the benefit being measured.
"""

from __future__ import annotations

import time

from ..config import RunConfig
from ..llm.router import LLMRouter
from ..sandbox.runner import run_probe
from ..trace.recorder import TrajectoryRecorder
from ..types import (
    AuditReport,
    Probe,
    RunStatus,
    Strategy,
    Triage,
    TriageOutcome,
    Verdict,
)
from .oracle import second_opinion
from .referee import asserted_expectation


def adjudicate_tests(
    *,
    case_id: str,
    spec: str,
    impl_src: str,
    tests: list[str],
    config: RunConfig,
    router: LLMRouter,
    recorder: TrajectoryRecorder,
    entrypoint: str = "",
    system_name: str = "agent_plus_oracle",
    upstream: AuditReport | None = None,
) -> tuple[AuditReport, list[str]]:
    """Filter ``tests`` down to those an independent reading of the spec upholds."""
    started = time.monotonic()
    recorder.stage_start(
        "adjudication",
        f"{len(tests)} test(s) from the upstream system, filtered by the Oracle alone",
    )

    kept: list[str] = []
    withdrawn = 0
    passing = 0

    for index, code in enumerate(tests, start=1):
        result = run_probe(
            probe_code=code, impl_source=impl_src, timeout_s=config.sandbox_timeout_s
        )
        recorder.tool_call(
            tool="sandbox.run_probe",
            args={"probe_id": f"X-{index:02d}", "code": code},
            result={"status": result.status.value, "assertion": result.assertion},
        )
        if result.status is not RunStatus.FAIL:
            # A test that does not fail is not an accusation, so there is
            # nothing to adjudicate.  It is still emitted: the grader's
            # soundness rule requires every emitted test to pass on the hidden
            # reference, and dropping the green ones here would quietly relax
            # that.
            passing += 1
            kept.append(code)
            continue

        probe = Probe(
            id=f"X-{index:02d}",
            obligation_id="OB-000",
            strategy=Strategy.EXAMPLE,
            rationale="produced by the upstream system",
            code=code,
        )
        verdict = second_opinion(
            spec=spec,
            probe=probe,
            expectation=asserted_expectation(code),
            entrypoint=entrypoint,
            verdict=Triage(
                outcome=TriageOutcome.UPHELD,
                reason="upstream system reported this as a defect",
                spec_supports_expectation=True,
            ),
            router=router,
            recorder=recorder,
            config=config,
        )
        if verdict.outcome is TriageOutcome.UPHELD:
            kept.append(code)
        else:
            withdrawn += 1

    recorder.stage_end(
        "adjudication",
        {"kept": len(kept), "withdrawn_by_oracle": withdrawn, "not_an_accusation": passing},
    )

    cost = router.cost
    cost.wall_ms = int((time.monotonic() - started) * 1000)
    if upstream is not None:
        cost = upstream.cost.merge(cost)

    report = AuditReport(
        case_id=case_id,
        system=system_name,
        verdict=Verdict.DEFECT if len(kept) > passing else Verdict.CLEAN,
        probes_run=len(tests),
        probes_discarded=withdrawn,
        withdrawn_by_oracle=withdrawn,
        cost=cost,
        notes=[
            "tests generated by the general-purpose agent, filtered by the "
            "specification-anchored Oracle; the Oracle can only remove a test"
        ],
    )
    return report, kept
