"""Render trajectories into a single self-contained HTML file.

Requirements this satisfies, in order:

* **Zero setup.** One file, no server, no CDN, no account. A judge double-clicks
  it and the trajectories are there, offline.
* **Readable as a narrative.** Steps in order, agent instructions visible,
  every tool call shown with what it returned, retries and human checkpoints
  called out rather than buried.
* **Honest.** It renders the JSONL verbatim; nothing is summarised away. The
  raw files sit next to it for anyone who prefers ``head``.
"""

from __future__ import annotations

import json
from pathlib import Path

_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Blindspot agent trajectories</title>
<style>
:root {
  color-scheme: light dark;
  --bg:#ffffff; --fg:#14161a; --muted:#5c6370; --line:#e3e6ea; --panel:#f7f8fa;
  --accent:#2f6feb; --red:#c0392b; --green:#1e7f4f; --amber:#a86800; --violet:#6b3fa0;
  --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root { --bg:#0f1115; --fg:#e6e8ec; --muted:#9aa3b2; --line:#242a33; --panel:#161a21;
          --accent:#6fa0ff; --red:#ff8b7a; --green:#5fd39b; --amber:#e0b050; --violet:#b98cf0; }
}
* { box-sizing:border-box }
body { margin:0; background:var(--bg); color:var(--fg);
       font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif }
header { padding:20px 24px; border-bottom:1px solid var(--line); position:sticky; top:0;
         background:var(--bg); z-index:5 }
h1 { margin:0 0 4px; font-size:19px; letter-spacing:-.01em }
.sub { color:var(--muted); font-size:13px }
.wrap { display:grid; grid-template-columns:320px 1fr; min-height:calc(100vh - 78px) }
nav { border-right:1px solid var(--line); overflow:auto; max-height:calc(100vh - 78px);
      padding:12px }
nav input { width:100%; padding:7px 9px; margin-bottom:10px; border:1px solid var(--line);
            border-radius:6px; background:var(--panel); color:var(--fg); font-size:13px }
nav button { display:block; width:100%; text-align:left; padding:8px 10px; margin-bottom:3px;
             border:0; border-radius:6px; background:transparent; color:var(--fg);
             cursor:pointer; font-size:13px; font-family:var(--mono) }
nav button:hover { background:var(--panel) }
nav button.on { background:var(--accent); color:#fff }
main { padding:18px 24px; overflow:auto; max-height:calc(100vh - 78px) }
.step { border:1px solid var(--line); border-radius:8px; margin-bottom:10px; overflow:hidden }
.step > summary { cursor:pointer; padding:9px 12px; display:flex; gap:10px; align-items:baseline;
                  background:var(--panel); list-style:none; font-size:13px }
.step > summary::-webkit-details-marker { display:none }
.n { color:var(--muted); font-family:var(--mono); min-width:32px }
.ev { font-family:var(--mono); font-weight:600 }
.ev.llm { color:var(--accent) } .ev.tool { color:var(--violet) }
.ev.retry { color:var(--amber) } .ev.human { color:var(--green) }
.ev.run { color:var(--fg) } .ev.stage { color:var(--muted) }
.meta { color:var(--muted); margin-left:auto; font-size:12px; font-family:var(--mono) }
.body { padding:10px 12px }
.lbl { font-size:11px; letter-spacing:.06em; text-transform:uppercase; color:var(--muted);
       margin:10px 0 4px }
pre { margin:0; padding:10px; background:var(--panel); border:1px solid var(--line);
      border-radius:6px; overflow-x:auto; font-family:var(--mono); font-size:12.5px;
      white-space:pre-wrap; word-break:break-word; max-height:460px; overflow-y:auto }
.pill { display:inline-block; padding:1px 7px; border-radius:20px; font-size:11px;
        border:1px solid var(--line); font-family:var(--mono) }
.pass{color:var(--green)} .fail{color:var(--red)} .error{color:var(--amber)}
.legend { color:var(--muted); font-size:12px; margin-bottom:12px }
.empty { color:var(--muted); padding:40px; text-align:center }
</style></head><body>
<header>
  <h1>Blindspot — agent trajectories</h1>
  <div class="sub">__COUNT__ runs · every model call, tool response, retry and human checkpoint, in order · generated by <code>blindspot trace</code></div>
</header>
<div class="wrap">
  <nav>
    <input id="q" placeholder="filter runs...">
    <div id="list"></div>
  </nav>
  <main>
    <div class="legend">Click a step to expand it. <span class="ev llm">llm.call</span> is a model call ·
      <span class="ev tool">tool.call</span> is deterministic (sandbox, AST, quote check) ·
      <span class="ev retry">verify.retry</span> is feedback that changed the next step ·
      <span class="ev human">human.checkpoint</span> is an escalation.</div>
    <div id="steps" class="empty">Select a run.</div>
  </main>
</div>
<script>
const RUNS = __DATA__;
const list = document.getElementById('list');
const steps = document.getElementById('steps');
const q = document.getElementById('q');
let current = null;

const esc = s => String(s ?? '').replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const cls = e => e.startsWith('llm') ? 'llm' : e.startsWith('tool') ? 'tool'
  : e.startsWith('verify') ? 'retry' : e.startsWith('human') ? 'human'
  : e.startsWith('run') ? 'run' : 'stage';

function block(label, value) {
  if (value === undefined || value === null || value === '') return '';
  const text = typeof value === 'string' ? value : JSON.stringify(value, null, 2);
  return `<div class="lbl">${esc(label)}</div><pre>${esc(text)}</pre>`;
}

function summaryOf(s) {
  const e = s.event;
  if (e === 'llm.call') return `${s['gen_ai.operation.name']} · ${s['gen_ai.request.model']}`;
  if (e === 'tool.call') return s['tool.name'];
  if (e === 'verify.retry') return `${s.reason} (attempt ${s.attempt})`;
  if (e === 'human.checkpoint') return `${s.resolved_by}: ${(s.question||'').slice(0,90)}`;
  if (e === 'agent.decision') return (s.what||'').slice(0,110);
  if (e === 'stage.start') return s.note || '';
  if (e === 'stage.end') return JSON.stringify(s.summary || {});
  if (e === 'run.end') return `${s.verdict} · ${s.findings} finding(s)`;
  if (e === 'note') return (s.message||'').slice(0,110);
  return '';
}

function detailOf(s) {
  const e = s.event;
  let out = '';
  if (e === 'llm.call') {
    out += block('agent instructions (system prompt)', s['prompt.system']);
    out += block('input', s['prompt.user']);
    out += block('model output', s.completion);
    out += block('usage', {input_tokens: s['gen_ai.usage.input_tokens'],
                           output_tokens: s['gen_ai.usage.output_tokens'],
                           attempt: s.attempt, cassette: s.cassette});
  } else if (e === 'tool.call') {
    out += block('arguments', s['tool.arguments']);
    out += block('tool response', s['tool.result']);
  } else if (e === 'human.checkpoint') {
    out += block('question', s.question);
    out += block('options', s.options);
    out += block('resolution', s.resolution ?? '(left open — not reported as a defect)');
  } else if (e === 'agent.decision') {
    out += block('decision', s.what); out += block('why', s.why); out += block('data', s.data);
  } else {
    const {format, step, event, run_id, case_id, system, stage, ...rest} = s;
    out += block('payload', rest);
  }
  return out;
}

function renderRun(run) {
  current = run.name;
  document.querySelectorAll('nav button').forEach(b =>
    b.classList.toggle('on', b.dataset.name === run.name));
  steps.className = '';
  steps.innerHTML = run.steps.map(s => {
    const status = (s['tool.result'] && s['tool.result'].status) || '';
    const pill = status ? `<span class="pill ${status}">${esc(status)}</span>` : '';
    return `<details class="step"><summary><span class="n">${s.step}</span>` +
      `<span class="ev ${cls(s.event)}">${esc(s.event)}</span>` +
      `<span>${esc(summaryOf(s))}</span>${pill}` +
      `<span class="meta">${esc(s.stage || '')}</span></summary>` +
      `<div class="body">${detailOf(s)}</div></details>`;
  }).join('');
  steps.scrollTop = 0;
}

function renderList() {
  const needle = q.value.toLowerCase();
  list.innerHTML = '';
  RUNS.filter(r => r.name.toLowerCase().includes(needle)).forEach(run => {
    const b = document.createElement('button');
    b.textContent = run.name;
    b.dataset.name = run.name;
    b.className = run.name === current ? 'on' : '';
    b.onclick = () => renderRun(run);
    list.appendChild(b);
  });
}

q.oninput = renderList;
renderList();
if (RUNS.length) renderRun(RUNS[0]);
</script></body></html>
"""


def load_trajectory(path: Path) -> list[dict]:
    steps: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            steps.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return steps


def render_index(files: list[Path], out: Path, *, max_bytes: int = 12_000_000) -> Path:
    """Inline every trajectory into one HTML file, newest-first, under a size cap."""
    runs: list[dict] = []
    budget = max_bytes
    for path in files:
        steps = load_trajectory(path)
        if not steps:
            continue
        payload = {"name": path.stem, "steps": steps}
        size = len(json.dumps(payload))
        if size > budget:
            # Keep the file openable rather than silently dropping runs: trim
            # this run's steps and say so.
            trimmed: list[dict] = list(steps[: max(10, len(steps) // 4)])
            payload["steps"] = trimmed
            trimmed.append(
                {
                    "step": 9999,
                    "event": "note",
                    "stage": "render",
                    "message": (
                        f"[trimmed by `blindspot trace` to stay under the "
                        f"{max_bytes // 1_000_000} MB page budget — the complete run is in "
                        f"{path.name}]"
                    ),
                }
            )
            size = len(json.dumps(payload))
        budget -= size
        runs.append(payload)
        if budget <= 0:
            break

    data = json.dumps(runs, ensure_ascii=False).replace("</script>", "<\\/script>")
    page = _TEMPLATE.replace("__DATA__", data).replace("__COUNT__", str(len(runs)))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding="utf-8")
    return out
